
const ChatTypes = {
  SET_CHAT_IN_GROUP: "SET_CHAT_IN_GROUP",
  ADD_CHAT_IN_GROUP: "ADD_CHAT_IN_GROUP",
  UPDATE_CHAT_IN_GROUP: "UPDATE_CHAT_IN_GROUP",
  REFRESH_CHAT_IN_GROUP: "REFRESH_CHAT_IN_GROUP",

  SET_ACTIVE_GROUP: "SET_ACTIVE_GROUP",

}


export default ChatTypes