
const ChatTypes = {
  SET_CHAT_IN_GROUP: "SET_CHAT_IN_GROUP",
  ADD_CHAT_IN_GROUP: "ADD_CHAT_IN_GROUP",
  UPDATE_CHAT_IN_GROUP: "UPDATE_CHAT_IN_GROUP",
  REFRESH_CHAT_IN_GROUP: "REFRESH_CHAT_IN_GROUP",

  LIKE_UNLIKE_MESSAGE: "LIKE_UNLIKE_MESSAGE",
  LIKE_UNLIKE_MESSAGE_SUCCESS: "LIKE_UNLIKE_MESSAGE_SUCCESS",
}


export default ChatTypes