
const ChatTypes = {
  GET_GROUP_CHAT: "GET_GROUP_CHAT",
  SET_CHAT_IN_GROUP: "SET_CHAT_IN_GROUP",
  ADD_CHAT_IN_GROUP: "ADD_CHAT_IN_GROUP",
  UPDATE_CHAT_IN_GROUP: "UPDATE_CHAT_IN_GROUP",
  REFRESH_CHAT_IN_GROUP: "REFRESH_CHAT_IN_GROUP",
  DELETE_CHAT_IN_GROUP_SUCCESS: "DELETE_CHAT_IN_GROUP_SUCCESS",
  UPDATE_CHAT_IN_GROUP_SUCCESS: "UPDATE_CHAT_IN_GROUP_SUCCESS",

  LIKE_UNLIKE_MESSAGE: "LIKE_UNLIKE_MESSAGE",
  LIKE_UNLIKE_MESSAGE_SUCCESS: "LIKE_UNLIKE_MESSAGE_SUCCESS",

  LIKE_UNLIKE_MESSAGE_EVENT: "LIKE_UNLIKE_MESSAGE_EVENT",
  LIKE_UNLIKE_MESSAGE_SUCCESS_EVENT: "LIKE_UNLIKE_MESSAGE_SUCCESS_EVENT",

  GET_EVENT_CHAT: "GET_EVENT_CHAT",
  SET_CHAT_IN_EVENT: "SET_CHAT_IN_EVENT",
  ADD_CHAT_IN_EVENT: "ADD_CHAT_IN_EVENT",
  UPDATE_CHAT_IN_EVENT: "UPDATE_CHAT_IN_EVENT",
  REFRESH_CHAT_IN_EVENT: "REFRESH_CHAT_IN_EVENT",
  DELETE_CHAT_IN_EVENT_SUCCESS: "DELETE_CHAT_IN_EVENT_SUCCESS",
  UPDATE_CHAT_IN_EVENT_SUCCESS: "UPDATE_CHAT_IN_EVENT_SUCCESS",

}


export default ChatTypes