
const otherTypes = {
  IS_LOADING: "IS_LOADING",
  LOADING_MSG: "LOADING_MSG",
  UPLOAD_FILE: "UPLOAD_FILE",
  CANCEL_UPLOAD: "CANCEL_UPLOAD",
  REFRESH_LANGUAGE: "REFRESH_LANGUAGE",
}


export default otherTypes