
const UserTypes = {
  DO_LOGOUT: "DO_LOGOUT",
  DO_LOGIN: "DO_LOGIN",
  DO_SIGN_UP: "DO_SIGN_UP",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_OTP: "VERIFY_OTP",
}


export default UserTypes