
const UserTypes = {
  DO_LOGOUT: "DO_LOGOUT",
  DO_LOGIN: "DO_LOGIN",
  DO_SIGN_UP: "DO_SIGN_UP",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_OTP: "VERIFY_OTP",
  CHECK_EMAIL: "CHECK_EMAIL",

  // Profile

  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_NOTIFICATION_SETTINGS: "UPDATE_NOTIFICATION_SETTINGS",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  SET_NOTIFICATION_SETTINGS: "SET_NOTIFICATION_SETTINGS",


  // Groups

  GET_MUTED_REPORTED_COUNT: "GET_MUTED_REPORTED_COUNT",
  GET_BLOCKED_MEMBERS: "GET_BLOCKED_MEMBERS",
  GET_MUTED_RESOURCES: "GET_MUTED_RESOURCES",

  BLOCK_UNBLOCK_RESOURCE: "BLOCK_UNBLOCK_RESOURCE",


}


export default UserTypes