export const Images = {
    ic_login_icon: require("./images/ic_login_icon.png"),
    ic_delete_user: require("./images/ic_delete_user.png"),
    ic_logo_name: require("./images/ic_logo_name.png"),
    ic_eye_open: require("./images/ic_eye_open.png"),
    ic_eye_closed: require("./images/ic_eye_closed.png"),
    ic_calender: require("./images/ic_calender.png"),
    ic_email_illustrator: require("./images/ic_email_illustrator.png"),
    ic_homepage: require("./images/ic_homepage.png"),
    ic_camera: require("./images/ic_camera.png"),
    ic_profile_image: require("./images/ic_profile_image.png"),
    ic_calender_2: require("./images/ic_calender_2.png"),
    ic_logout: require("./images/ic_logout.png"),
    ic_lock: require("./images/ic_lock.png"),
    ic_key: require("./images/ic_key.png"),
    ic_blocked_members: require("./images/ic_blocked_members.png"),
    ic_muted: require("./images/ic_muted.png"),
    ic_right: require("./images/ic_right.png"),
    ic_home_profile: require("./images/ic_home_profile.png"),
    ic_setting: require("./images/ic_setting.png"),
    ic_lens: require("./images/ic_lens.png"),
    ic_group_icon: require("./images/ic_group_icon.png"),
    ic_marker: require("./images/ic_marker.png"),
    ic_left: require("./images/ic_left.png"),
    ic_search_location: require("./images/ic_search_location.png"),
    ic_search_send: require("./images/ic_search_send.png"),
    ic_location: require("./images/ic_location.png"),
    // ic_location: require("./images/ic_location.png"),

}